import {
  AlertTriangle,
  ArrowRight,
  Briefcase,
  Calendar,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  MapPin,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  ReceiptTextIcon,
  Settings,
  SunMedium,
  Trash,
  User,
  User2Icon,
  UsersRound,
  X,
} from 'lucide-react';

import BookSVG from '@/assets/book.svg';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UsersRound,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  calendar: Calendar,
  location: MapPin,
  quote: ReceiptTextIcon,
  job: Briefcase,
  clock: CalendarClock,
  booksvg: BookSVG,
};
